create table if not exists public.news (
    id bigint generated by default as identity primary key,
    title varchar(512) not null,
    url varchar(512) not null unique,
    created_at timestamptz not null default now(),
    article_data jsonb not null default '{}'::jsonb
);

create table if not exists public.keyword (
    id bigint generated by default as identity primary key,
    word varchar(255) not null unique,
    total_count int4 not null default 0,
    article_count int4 not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.article_keyword (
    id bigint generated by default as identity primary key,
    news_id bigint not null references public.news(id) on delete cascade,
    keyword_id bigint not null references public.keyword(id) on delete cascade,
    count int4 not null,
    created_at timestamptz not null default now(),
    constraint unique_news_keyword unique (news_id, keyword_id)
);

create table if not exists public.news_analysis (
    id bigint generated by default as identity primary key,
    news_id bigint not null unique references public.news(id) on delete cascade,
    summary text not null,
    ad_probability numeric(5, 2) not null default 0.00,
    is_clickbait bool not null default false,
    analyzed_at timestamptz not null default now(),
    named_entities jsonb not null default '[]'::jsonb
);

create index if not exists idx_news_created_at on public.news(created_at desc);
create index if not exists idx_keyword_updated_at on public.keyword(updated_at desc);
create index if not exists idx_article_keyword_news_id on public.article_keyword(news_id);
create index if not exists idx_article_keyword_keyword_id on public.article_keyword(keyword_id);
