create table if not exists public.news (
    id bigint generated by default as identity primary key,
    title varchar(512) not null,
    url varchar(512) not null unique,
    created_at timestamptz not null default now(),
    article_data jsonb not null default '{}'::jsonb
);

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    login_id varchar(60) not null unique,
    password varchar(512),
    nickname varchar(50) not null,
    profile_image varchar(512),
    provider varchar(20),
    provider_id varchar(255),
    role varchar(20) not null default 'ROLE_USER',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table if exists public.users
    add column if not exists login_id varchar(60);

update public.users
set login_id = lower(split_part(email, '@', 1))
where login_id is null and email is not null;

alter table if exists public.users
    alter column login_id set not null;

create unique index if not exists idx_users_login_id on public.users(login_id);

create table if not exists public.keyword (
    id bigint generated by default as identity primary key,
    word varchar(255) not null unique,
    total_count int4 not null default 0,
    article_count int4 not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.article_keyword (
    id bigint generated by default as identity primary key,
    news_id bigint not null references public.news(id) on delete cascade,
    keyword_id bigint not null references public.keyword(id) on delete cascade,
    count int4 not null,
    created_at timestamptz not null default now(),
    constraint unique_news_keyword unique (news_id, keyword_id)
);

create table if not exists public.news_analysis (
    id bigint generated by default as identity primary key,
    news_id bigint not null unique references public.news(id) on delete cascade,
    summary text not null,
    ad_probability numeric(5, 2) not null default 0.00,
    is_clickbait bool not null default false,
    analyzed_at timestamptz not null default now(),
    named_entities jsonb not null default '[]'::jsonb
);

create table if not exists public.news_interaction (
    id bigint generated by default as identity primary key,
    client_user_id varchar(80) not null,
    news_id bigint not null references public.news(id) on delete cascade,
    interaction_type varchar(30) not null,
    weight int4 not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint unique_client_news_interaction unique (client_user_id, news_id, interaction_type)
);

create index if not exists idx_news_created_at on public.news(created_at desc);
create index if not exists idx_keyword_updated_at on public.keyword(updated_at desc);
create index if not exists idx_article_keyword_news_id on public.article_keyword(news_id);
create index if not exists idx_article_keyword_keyword_id on public.article_keyword(keyword_id);
create index if not exists idx_news_interaction_news_id on public.news_interaction(news_id);
create index if not exists idx_news_interaction_client_user_id on public.news_interaction(client_user_id);
create index if not exists idx_news_interaction_client_news on public.news_interaction(client_user_id, news_id);
create index if not exists idx_news_interaction_news_client on public.news_interaction(news_id, client_user_id);
